export interface Project {
  id: string;
  name: string;
  location: string;
  targetCompletion: string;
  budget: string;
  overallProgress: number;
  manager: string;
  status: 'Aktif' | 'Selesai' | 'Tertunda';
  description: string;
  lat?: number;
  lng?: number;
}

export type ReportCategory = 'Struktur' | 'Arsitektur' | 'Mekanikal & Elektrikal' | 'Finishing' | 'Kesehatan & Keselamatan (K3)' | 'Lainnya';

export type ReportStatus = 'Sedang Berjalan' | 'Selesai' | 'Tertunda' | 'Butuh Tindakan';

export interface ProjectProgressReport {
  id: string;
  projectId: string;
  projectName: string;
  location: string;
  reporterName: string;
  reporterRole: 'Pekerja Lapangan' | 'Pengawas' | 'Kontraktor';
  date: string;
  progressPercentage: number;
  description: string;
  photoUrl: string; // Base64 or ObjectURL string
  photoUrls?: string[]; // Multiple photos support
  category: ReportCategory;
  status: ReportStatus;
  timestamp: number;
  approvalStatus?: 'Pending' | 'Disetujui' | 'Perlu Revisi';
  managementFeedback?: string;
  isOfflineQueued?: boolean;
}

export interface NotificationAlert {
  id: string;
  title: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  timestamp: number;
  read: boolean;
  reportId?: string;
}

export type ActiveRole = 'Pekerja Lapangan' | 'Tim Manajemen';

export interface SchedulerSettings {
  enabled: boolean;
  frequency: 'weekly' | 'daily' | 'monthly';
  dayOfWeek: number; // 0-6 (Sunday-Saturday)
  time: string; // "HH:MM"
  recipientEmail: string;
  includePdf: boolean;
  includeSheets: boolean;
  lastRunTimestamp?: number;
  nextRunTimestamp?: number;
}

export interface ProjectWeeklyMetrics {
  projectId: string;
  projectName: string;
  reportCount: number;
  startingProgress: number;
  currentProgress: number;
  progressGained: number;
  status: string;
}

export interface CompiledWeeklySummary {
  id: string;
  title: string;
  startDate: string;
  endDate: string;
  compiledAt: string;
  totalReports: number;
  averageProgress: number;
  progressGained: number;
  projectBreakdown: ProjectWeeklyMetrics[];
  categoryBreakdown: { category: string; count: number }[];
  keyHighlights: string[];
  pendingApprovals: number;
  isAutoGenerated: boolean;
}

